behaviors:
  ShakeIt:
    trainer_type: ppo
    hyperparameters:
      batch_size: 32                      # before: 10
      buffer_size: 2048                   # before: 100
      learning_rate: 0.001
      beta: 0.001
      epsilon: 0.1
      lambd: 0.99
      num_epoch: 3
      learning_rate_schedule: linear
    network_settings:
      normalize: true                      #default: true
      hidden_units: 256
      num_layers: 5
      vis_encode_type: simple
    reward_signals:
      extrinsic:
        gamma: 0.9
        strength: 1.0
    keep_checkpoints: 5
    max_steps: 500000
    time_horizon: 1000                        #default:1000
    summary_freq: 5000
    threaded: true
    #init_path: E:\data\HANLAB\ml_agent\ml-agents-release_15\SiMix00\ShakeIt.nn
